apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
spec:
  ingressClassName: {{ .Values.className }}
  rules:
  - host: {{ .Values.secondService.host }}
    http:
      paths:
        - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.firstService.name }}
            port:
              number: {{ .Values.firstService.portNumber }}

