deployment:
  name: "weatherapp"
  replicas: "1"
  image: "michaelaviram/app:20"
  containerPort: "8989"
  configmap: "green"
  configmapKey: "BG_COLOR"
service:
  name: "weatherapp-service"
  port: "8989"
  targetPort: "8989"
